[bridge_deck]
is_present = true

[[bridge_deck.structures]]
structure_name = "1500_571_1"

high_chord_upstream_left_bank = 1287.20
low_chord_upstream_left_bank = 1286.93
high_chord_upstream_right_bank = 1287.20
low_chord_upstream_right_bank = 1286.93

high_chord_downstream_left_bank = 1287.20
low_chord_downstream_left_bank = 1286.70
high_chord_downstream_right_bank = 1287.20
low_chord_downstream_right_bank = 1286.70

bridge_width = 9.98

upstream_point_1_x = 536728.47
upstream_point_1_y = 4168022.57
upstream_point_2_x = 536726.90
upstream_point_2_y = 4168022.56
downstream_point_1_x = 536728.71
downstream_point_1_y = 4168012.58
downstream_point_2_x = 536727.20
downstream_point_2_y = 4168012.59

deck_distance = 0.1
deck_weir_coefficient = 1.4
deck_skew = 0.0
deck_max_submerge = 0.98
htab_hwmax = 1287.29
htab_max_flow = 50.0
preserve_endpoint_order = true
opening_station_method = "csv_override"
use_bank_point_station = true
